### ISSUE TITLE
Automatic refresh on page load

### ISSUE THREAD

**Issue by max78bri** [wp-net/WordPressXF#1]
Good evening, 
someone has been asking how to automatically load the posts when you load the page without having to pull down the screen?
I do not know how to invoke the asynchronous call without using a "command" command.
Thanks

**Comment by tsjdev-apps** [comment]
Currently I didn't find a good way for auto refresh. Maybe we can introduce an extended splash screen which shows an loading indicator while getting the first bunch of data. But I will think about an option to enable automatic refresh on page loading.

**Comment by max78bri** [comment]
An extended splash screen is a nice idea also because currently in android there is not and would make the application more appealing.
However compliments for the project that already so it is very interesting.
Sorry for my English, but I help me with a translator .....

**Comment by tsjdev-apps** [comment]
I will take a look at this and will inform you, when I've updated the code.

**Comment by tsjdev-apps** [comment]
I've introduced a SplashScreen to load the news.
