### ISSUE TITLE
What modifications are required to add Windows-UWP functionality?

### ISSUE THREAD

**Issue by atultiwari** [wp-net/WordPressXF#2]
Hi,

First of all, thank you very much for sharing this code. This is very helpful for people like me, who only know basics.

I would like to know, how to make this code work for windows uwp app using xamaring forms only. I tried to add new uwp project and made necessary changes as mentioned on [xamarin guide](https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/), but when I run the app, it loads an empty list, clicking on which crashes the app. No specific error is shown

Can you please help me with this.

Thanks
Regards,
Atul

**Comment by tsjdev-apps** [comment]
Hi,

there is a solution by @ThomasPe in this [repository](https://github.com/wp-net/WordPressUWP).
Currently this Xamarin.Forms project will only contain an Android and an iOS solution.

I will think about integrating the UWP version as well.

Greetings,
 Sebastian

**Comment by tsjdev-apps** [comment]
Hello @atultiwari,

with the commit `6b28a94` there is now also a UWP version included in the project. But it is only a basic implementation, so maybe you should refer to the [project](https://github.com/wp-net/WordPressUWP) by @ThomasPe.

Greetings,
 Sebastian
