### ISSUE TITLE
Does not Compile on Lastet Visual Studio 2017

### ISSUE THREAD

**Issue by Kilmanagh** [wp-net/WordPressXF#3]
I am getting: error XA4212: Type `Android.Support.V4.App.JobIntentService/JobServiceEngineImpl` implements `Android.Runtime.IJavaObject` but does not inherit `Java.Lang.Object` or `Java.Lang.Throwable`. This is not supported.	WordPressXF.Android

There is a Xamarim topic about this error  at: https://forums.xamarin.com/discussion/72639/implementing-java-interfaces-without-inheriting-java-lang-object-should-fail-early.

However I am not sure where it needs to go in this code.

Thank you.

**Comment by tsjdev-apps** [comment]
Hi @Kilmanagh,

I've updated today all the NuGet Packages of the project and I don't have any issues with the described problem. Can you please try again to clone the new `master` branch and take a look?

Thanks.

**Comment by tsjdev-apps** [comment]
I will close this issue. If you have another issue with the project so please open a new one. Thanks.
